version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 povertymappingapp.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=povertymappingapp.settings
    networks:
      - app_network

  nginx:
    image: nginx
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 inside the container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
