version: '3'

services:
  webapp:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 povertymappingapp.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=povertymappingapp.settings
    networks:
      - app_network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webapp
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
